#ifndef TERRACE_OF_ENDLESS_SPRING_H_
#define TERRACE_OF_ENDLESS_SPRING_H_

#define MAX_ENCOUNTER 4

enum eData
{
	DATA_PROTECTORS,
	DATA_TSULONG,
	DATA_LEI_SHI,
	DATA_SHA_OF_FEAR,

    DATA_ANCIENT_ASANI,
    DATA_ANCIENT_REGAIL,
    DATA_PROTECTOR_KAOLAN,
    DATA_MINION_OF_FEAR_CONTROLLER,

    DATA_PURE_LIGHT_TERRACE,
    
    DATA_CACHE_OF_TSULONG_10,
    DATA_CACHE_OF_TSULONG_25,
    DATA_CACHE_OF_TSULONG_10H,
    DATA_CACHE_OF_TSULONG_25H,

    DATA_BOX_OF_FANCY_STUFF_10,
    DATA_BOX_OF_FANCY_STUFF_25,
    DATA_BOX_OF_FANCY_STUFF_10H,
    DATA_BOX_OF_FANCY_STUFF_25H,
};

enum eSpells
{
    SPELL_RITUAL_OF_PURIFICATION = 126848
};

enum eActions
{
    ACTION_START_TSULONG_WAYPOINT = 1,
    ACTION_INTRO_FINISHED = 2
};

enum eCreatures
{
    // Protectors of the Endless
    NPC_ANCIENT_ASANI               = 60586,
    NPC_ANCIENT_REGAIL              = 60585,
    NPC_PROTECTOR_KAOLAN            = 60583,
    NPC_DEFILED_GROUND              = 60906,
    NPC_COALESCED_CORRUPTION        = 60886,
    NPC_MINION_OF_FEAR_CONTROLLER   = 60957,
    NPC_MINION_OF_FEAR              = 60885,

    // Tsulong
    NPC_TSULONG                     = 62442,

    // Lei Shi
    NPC_LEI_SHI                     = 62983,
    NPC_ANIMATED_PROTECTOR          = 62995,
    NPC_LEI_SHI_HIDDEN              = 63099,

    // Sha of Fear
    NPC_SHA_OF_FEAR                 = 60999,
    NPC_PURE_LIGHT_TERRACE          = 60788,

    // Thrashs
    NPC_APPARITION_OF_FEAR          = 64368,
    NPC_APPARITION_OF_TERROR        = 66100,
    NPC_NIGHT_TERRORS               = 64390,
    NPC_NIGHT_TERROR_SUMMON         = 64393
};

enum eGameObjects
{
    GOB_WALL_OF_COUNCILS_VORTEX = 214854,
    GOB_COUNCILS_VORTEX         = 214853,

    GOB_WALL_OF_LEI_SHI         = 214852,
    GOB_LEI_SHIS_VORTEX         = 214851,

    GO_BOX_OF_FANCY_STUFF_10    = 213073, 
    GO_BOX_OF_FANCY_STUFF_25    = 213074, 
    GO_BOX_OF_FANCY_STUFF_10H   = 213075, 
    GO_BOX_OF_FANCY_STUFF_25H   = 213076, 

    GO_CACHE_OF_THULONG_10      = 212922, 
    GO_CACHE_OF_THULONG_25      = 215355, 
    GO_CACHE_OF_THULONG_10H     = 215356, 
    GO_CACHE_OF_THULONG_25H     = 215357,
};

enum ePhases
{
};

enum eWeapons
{
};

enum eEvents
{
};

enum eTypes
{
    INTRO_DONE
};

enum eTimers
{
	TIMER_TSULONG_SPAWN	= 10000,
};

const Position enterPos = {-1019.59f, -3135.37f, 26.85f, 1.47f};

#endif // TERRACE_OF_ENDLESS_SPRING_H_
